In [65]:
import pandas as pd
import json
from datetime import datetime

In [ ]:
#red in a table of state populations
populations = pd.read_csv('state_populations.csv',index_col=0).T
populations

In [92]:
#read the data
data = pd.read_csv( 'SlateGunDeaths.csv').fillna(0)
#fix a typo in the state names for consistency
data['state'] = data['state'].apply(lambda x: x.upper())
data

,victimID,date,name,gender,age,ageGroup,city,state,lat,lng,url
0,1,2012-12-14,Antida Archuleta,F,20.0,3.0,Westminster,CO,39.893668,-105.072112,http://www.9news.com/rss/story.aspx?storyid=30...
1,2,2012-12-14,Charlotte Bacon,F,6.0,1.0,Newtown,CT,41.412323,-73.311424,http://www.cnn.com/2012/12/15/us/connecticut-s...
2,3,2012-12-14,Olivia Engel,F,6.0,1.0,Newtown,CT,41.412323,-73.311424,http://www.cnn.com/2012/12/15/us/connecticut-s...
3,4,2012-12-14,Ana Marquez-Greene,F,6.0,1.0,Newtown,CT,41.412323,-73.311424,http://www.cnn.com/2012/12/15/us/connecticut-s...
4,5,2012-12-14,Dylan Hockley,M,6.0,1.0,Newtown,CT,41.412323,-73.311424,http://www.cnn.com/2012/12/15/us/connecticut-s...
...,...,...,...,...,...,...,...,...,...,...,...
12065,13303,2013-12-31,0,M,0.0,3.0,Camden,NJ,39.944844,-75.119869,http://www.nj.com/camden/index.ssf/2013/12/2_s...
12066,13305,2013-12-31,0,F,43.0,3.0,Andover,MN,45.233298,-93.291341,http://www.startribune.com/local/north/2382350...
12067,13307,2013-12-31,Damien Toney Jr.,M,20.0,3.0,Santa Rosa,CA,38.405884,-122.794477,http://www.sfgate.com/crime/article/Man-shot-t...
12068,13308,2013-12-31,Donald Eason,M,22.0,3.0,Baltimore,MD,39.290861,-76.610807,http://www.baltimoresun.com/news/maryland/crim...
12069,13309,2013-12-31,0,M,0.0,3.0,Riverside,CA,33.953355,-117.396162,http://losangeles.cbslocal.com/2013/12/31/man-...

In [93]:
#process dates into individual day, month, year and ordinal timestamp to make sorting and filtering easier
dates = data['date'].apply(lambda x: datetime.strptime(x,'%Y-%m-%d'))
data['year'] = dates.apply(lambda x: x.year)
data['day'] = dates.apply(lambda x: x.day)
data['month'] = dates.apply(lambda x: x.month)
data['timestamp'] = dates.apply(lambda x: x.date().toordinal())
data

,victimID,date,name,gender,age,ageGroup,city,state,lat,lng,url,year,day,month,timestamp
0,1,2012-12-14,Antida Archuleta,F,20.0,3.0,Westminster,CO,39.893668,-105.072112,http://www.9news.com/rss/story.aspx?storyid=30...,2012,14,12,734851
1,2,2012-12-14,Charlotte Bacon,F,6.0,1.0,Newtown,CT,41.412323,-73.311424,http://www.cnn.com/2012/12/15/us/connecticut-s...,2012,14,12,734851
2,3,2012-12-14,Olivia Engel,F,6.0,1.0,Newtown,CT,41.412323,-73.311424,http://www.cnn.com/2012/12/15/us/connecticut-s...,2012,14,12,734851
3,4,2012-12-14,Ana Marquez-Greene,F,6.0,1.0,Newtown,CT,41.412323,-73.311424,http://www.cnn.com/2012/12/15/us/connecticut-s...,2012,14,12,734851
4,5,2012-12-14,Dylan Hockley,M,6.0,1.0,Newtown,CT,41.412323,-73.311424,http://www.cnn.com/2012/12/15/us/connecticut-s...,2012,14,12,734851
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12065,13303,2013-12-31,0,M,0.0,3.0,Camden,NJ,39.944844,-75.119869,http://www.nj.com/camden/index.ssf/2013/12/2_s...,2013,31,12,735233
12066,13305,2013-12-31,0,F,43.0,3.0,Andover,MN,45.233298,-93.291341,http://www.startribune.com/local/north/2382350...,2013,31,12,735233
12067,13307,2013-12-31,Damien Toney Jr.,M,20.0,3.0,Santa Rosa,CA,38.405884,-122.794477,http://www.sfgate.com/crime/article/Man-shot-t...,2013,31,12,735233
12068,13308,2013-12-31,Donald Eason,M,22.0,3.0,Baltimore,MD,39.290861,-76.610807,http://www.baltimoresun.com/news/maryland/crim...,2013,31,12,735233
12069,13309,2013-12-31,0,M,0.0,3.0,Riverside,CA,33.953355,-117.396162,http://losangeles.cbslocal.com/2013/12/31/man-...,2013,31,12,735233

In [96]:
#loop through the data get aggregated statistics
statedata = []
citydata = []
#groupby returns a touple (key, dataframe[dataframe.groubyargument == key])
for state, statedf in data.groupby('state'):
    #get state information
    all_ids = statedf['victimID'].values.tolist()
    #remove spaces from the state name so it's easier to use as a lookup key in jquery-style selectors later on
    statename = populations.loc[state.upper()]['state'].replace(' ','_')
    state_male_count = statedf[statedf.gender == 'M'].shape[0]
    state_entry = {
        'population': populations.loc[state.upper()]['pop_2014'],
        'abreviation': state,
        'state': statename,
        'count': statedf.shape[0],
        'male_count': state_male_count,
        'ids': all_ids
    }
    statedata.append(state_entry)
    #loop through each wcity within the state
    for city, citydf in statedf.groupby('city'):
        lat = citydf.iloc[0]['lat']
        lng = citydf.iloc[0]['lng']
        all_ids = citydf['victimID'].values.tolist()
        male_count = citydf[citydf.gender == 'M'].shape[0]
        citykey = city.replace(' ','_') + '_' + statename
        city_entry = {
            'key': city + '_' + statename,
            'lat': lat,
            'lng': lng,
            'city': city,
            'state': statename,
            'count': citydf.shape[0],
            'male_count': male_count,
            'ids': all_ids
        }
        citydata.append(city_entry)
#look at state data
pd.DataFrame(statedata)

,population,abreviation,state,count,male_count,ids
0,736732,AK,Alaska,33,25,"[329, 2329, 472, 2273, 2237, 2142, 2198, 2587,..."
1,4849377,AL,Alabama,274,228,"[44, 45, 46, 47, 48, 165, 198, 199, 257, 258, ..."
2,2966369,AR,Arkansas,134,110,"[10258, 200, 1333, 369, 431, 1713, 1718, 518, ..."
3,6731484,AZ,Arizona,248,208,"[49, 1889, 166, 167, 229, 259, 330, 403, 404, ..."
4,38802500,CA,California,1447,1281,"[1337, 50, 51, 52, 53, 54, 1462, 73, 74, 1421,..."
5,5355866,CO,Colorado,146,106,"[1, 1342, 128, 129, 130, 131, 172, 207, 334, 3..."
6,3596677,CT,Connecticut,110,83,"[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 1..."
7,658893,DC,District_of_Columbia,105,96,"[75, 103, 173, 233, 264, 291, 375, 433, 477, 9..."
8,935614,DE,Delaware,41,33,"[292, 697, 814, 1605, 2101, 1921, 1906, 1907, ..."
9,19893297,FL,Florida,778,634,"[30, 55, 56, 104, 105, 132, 133, 148, 174, 175..."
10,10097343,GA,Georgia,390,316,"[76, 106, 1465, 149, 150, 210, 294, 295, 296, ..."
11,1419561,HI,Hawaii,13,7,"[436, 1002, 1987, 1988, 3061, 7807, 6572, 8115..."
12,3107126,IA,Iowa,56,47,"[2309, 2319, 241, 437, 2304, 1412, 2269, 2046,..."
13,1634464,ID,Idaho,29,23,"[639, 640, 1040, 1143, 1170, 2138, 2882, 2262,..."
14,12880580,IL,Illinois,615,552,"[57, 58, 77, 78, 107, 3320, 179, 178, 238, 239..."
15,6596855,IN,Indiana,344,296,"[1321, 5133, 108, 1183, 134, 151, 152, 211, 21..."
16,2904021,KS,Kansas,112,90,"[80, 81, 109, 242, 271, 438, 439, 440, 617, 64..."
17,4413457,KY,Kentucky,179,139,"[2321, 213, 272, 298, 1482, 380, 441, 442, 489..."
18,4649676,LA,Louisiana,424,369,"[82, 83, 84, 111, 1467, 136, 180, 4537, 243, 3..."
19,6745408,MA,Massachusetts,98,87,"[60, 340, 416, 446, 447, 756, 1035, 1319, 1565..."
20,5976407,MD,Maryland,332,295,"[59, 85, 86, 4353, 137, 155, 4621, 181, 273, 3..."
21,1330089,ME,Maine,26,21,"[444, 445, 571, 2263, 1952, 4941, 4942, 3078, ..."
22,9909877,MI,Michigan,491,409,"[31, 32, 2414, 61, 7000, 7001, 113, 114, 115, ..."
23,5457173,MN,Minnesota,105,91,"[116, 2796, 274, 2984, 1575, 670, 731, 1318, 8..."
24,6063589,MO,Missouri,355,292,"[62, 89, 90, 117, 118, 119, 120, 156, 275, 276..."
25,2994079,MS,Mississippi,141,110,"[87, 88, 183, 1476, 1477, 245, 246, 247, 1317,..."
26,1023579,MT,Montana,32,31,"[343, 452, 1793, 1308, 1720, 1919, 2250, 2564,..."
27,9943964,NC,North_Carolina,438,359,"[35, 36, 37, 64, 95, 1179, 1180, 187, 214, 216..."
28,739482,ND,North_Dakota,8,7,"[1970, 2368, 2999, 5032, 7212, 9190, 12175, 12..."
29,1881503,NE,Nebraska,54,48,"[1866, 499, 535, 574, 2313, 952, 1387, 1772, 1..."
30,1326813,NH,New_Hampshire,14,13,"[92, 385, 4480, 2824, 3371, 5402, 7873, 7874, ..."
31,8938175,NJ,New_Jersey,278,252,"[63, 93, 1214, 2327, 3403, 304, 1483, 386, 417..."
32,2085572,NM,New_Mexico,88,69,"[94, 305, 344, 345, 388, 500, 538, 576, 1146, ..."
33,2839099,NV,Nevada,121,99,"[33, 34, 91, 303, 453, 618, 1418, 708, 791, 79..."
34,19746227,NY,New_York,379,329,"[1460, 1461, 2318, 2316, 138, 184, 185, 186, 2..."
35,11594163,OH,Ohio,497,421,"[2323, 38, 65, 96, 97, 121, 122, 157, 4583, 45..."
36,3878051,OK,Oklahoma,183,148,"[66, 67, 68, 69, 123, 139, 140, 218, 219, 250,..."
37,3970239,OR,Oregon,85,66,"[2303, 283, 543, 715, 716, 770, 1158, 1123, 13..."
38,12787209,PA,Pennsylvania,570,492,"[70, 1441, 1463, 124, 125, 126, 1468, 141, 142..."
39,1055173,RI,Rhode_Island,25,19,"[1221, 1222, 3054, 3055, 3056, 3305, 3505, 350..."
40,4832482,SC,South_Carolina,236,176,"[98, 2533, 192, 193, 225, 316, 352, 393, 394, ..."
41,853175,SD,South_Dakota,17,16,"[143, 353, 2325, 595, 771, 2272, 4927, 3502, 5..."
42,6549352,TN,Tennessee,290,237,"[39, 40, 2326, 1756, 194, 1783, 1784, 317, 323..."
43,26956958,TX,Texas,988,806,"[41, 1459, 99, 100, 101, 4556, 1469, 144, 4555..."
44,2942902,UT,Utah,54,41,"[42, 43, 1102, 288, 289, 684, 685, 826, 1830, ..."
45,8326289,VA,Virginia,282,235,"[2324, 127, 145, 161, 162, 163, 1332, 290, 324..."
46,626562,VT,Vermont,15,11,"[356, 428, 549, 2246, 5689, 5762, 5763, 7047, ..."
47,7061530,WA,Washington,143,126,"[102, 227, 228, 254, 255, 326, 367, 402, 513, ..."
48,5757564,WI,Wisconsin,166,138,"[72, 1464, 1470, 1471, 164, 327, 430, 514, 515..."
49,1850326,WV,West_Virginia,65,56,"[256, 429, 627, 1255, 1316, 1256, 860, 928, 14..."
50,584153,WY,Wyoming,16,10,"[1066, 2551, 2663, 2664, 2665, 3164, 3366, 493..."

In [97]:
#look at data aggregated by city
pd.DataFrame(citydata)

,key,lat,lng,city,state,count,male_count,ids
0,Anchorage_Alaska,61.218056,-149.900281,Anchorage,Alaska,9,9,"[2273, 2142, 2198, 4476, 7221, 7471, 10673, 11..."
1,Chugiak_Alaska,61.388889,-149.481944,Chugiak,Alaska,2,1,"[10552, 10553]"
2,Cooper Landing_Alaska,60.495261,-149.847857,Cooper Landing,Alaska,1,1,[12459]
3,Delta Junction_Alaska,64.061926,-145.688043,Delta Junction,Alaska,1,0,[11014]
4,Fairbanks_Alaska,64.829002,-147.669917,Fairbanks,Alaska,4,2,"[2329, 2237, 3771, 10761]"
...,...,...,...,...,...,...,...,...
3344,Green River_Wyoming,41.529093,-109.466474,Green River,Wyoming,1,1,[3164]
3345,Jackson Hole_Wyoming,43.684122,-110.443617,Jackson Hole,Wyoming,1,1,[4936]
3346,Lander_Wyoming,42.833075,-108.730702,Lander,Wyoming,1,0,[9638]
3347,Natrona_Wyoming,43.029687,-106.809216,Natrona,Wyoming,1,1,[10104]
3348,Yellowstone_Wyoming,45.778025,-108.547300,Yellowstone,Wyoming,1,0,[8857]

In [98]:
#stick the dataframes into a json grouped by aggregated and unaggregated fiels
#of form {'victimID/state/city+state': {key: value, key2: value2}, {}, ...} etc
all_data = {
    'victims': data.to_dict(orient = 'records'),
    'states': statedata,
    'cities': citydata
}
all_data

{'victims': [{'victimID': 1,
   'date': '2012-12-14',
   'name': 'Antida Archuleta',
   'gender': 'F',
   'age': 20.0,
   'ageGroup': 3.0,
   'city': 'Westminster',
   'state': 'CO',
   'lat': 39.8936685,
   'lng': -105.072111818405,
   'url': 'http://www.9news.com/rss/story.aspx?storyid=305252',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 2,
   'date': '2012-12-14',
   'name': 'Charlotte Bacon',
   'gender': 'F',
   'age': 6.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 3,
   'date': '2012-12-14',
   'name': 'Olivia Engel',
   'gender': 'F',
   'age': 6.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 4,
   'date': '2012-12-14',
   'name': 'Ana Marquez-Greene',
   'gender': 'F',
   'age': 6.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 5,
   'date': '2012-12-14',
   'name': 'Dylan Hockley',
   'gender': 'M',
   'age': 6.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 6,
   'date': '2012-12-14',
   'name': 'Madeline Hsu',
   'gender': 'F',
   'age': 6.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 7,
   'date': '2012-12-14',
   'name': 'Catherine Hubbard',
   'gender': 'F',
   'age': 6.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 8,
   'date': '2012-12-14',
   'name': 'Jesse Lewis',
   'gender': 'M',
   'age': 6.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 9,
   'date': '2012-12-14',
   'name': 'James Mattioli',
   'gender': 'M',
   'age': 6.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 10,
   'date': '2012-12-14',
   'name': 'Emilie Parker',
   'gender': 'F',
   'age': 6.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 11,
   'date': '2012-12-14',
   'name': 'Jack Pinto',
   'gender': 'M',
   'age': 6.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 12,
   'date': '2012-12-14',
   'name': 'Noah Pozner',
   'gender': 'M',
   'age': 6.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 13,
   'date': '2012-12-14',
   'name': 'Caroline Previdi',
   'gender': 'F',
   'age': 6.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 14,
   'date': '2012-12-14',
   'name': 'Jessica Rekos',
   'gender': 'F',
   'age': 6.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 15,
   'date': '2012-12-14',
   'name': 'Avielle Richman',
   'gender': 'F',
   'age': 6.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 16,
   'date': '2012-12-14',
   'name': 'Benjamin Wheeler',
   'gender': 'M',
   'age': 6.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 17,
   'date': '2012-12-14',
   'name': 'Allison Wyatt',
   'gender': 'F',
   'age': 6.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 18,
   'date': '2012-12-14',
   'name': 'Daniel Barden',
   'gender': 'M',
   'age': 7.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 10258,
   'date': '2012-12-14',
   'name': 'Debbie Ford',
   'gender': 'F',
   'age': 47.0,
   'ageGroup': 3.0,
   'city': 'Conway',
   'state': 'AR',
   'lat': 35.0886963,
   'lng': -92.4421011,
   'url': 'http://www.katv.com/story/23666951/conway-man-pleads-to-manslaughter-in-shooting-of-2',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 19,
   'date': '2012-12-14',
   'name': 'Josephine Gay',
   'gender': 'F',
   'age': 7.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 2323,
   'date': '2012-12-14',
   'name': 'Robert Hunt',
   'gender': 'M',
   'age': 57.0,
   'ageGroup': 3.0,
   'city': 'Chester',
   'state': 'OH',
   'lat': 39.0875777,
   'lng': -81.9226372,
   'url': 'http://www.wsaz.com/news/headlines/BREAKING-NEWS-Three-Shot-in-Meigs-County-Ohio-183542661.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 20,
   'date': '2012-12-14',
   'name': 'Chase Kowalski',
   'gender': 'M',
   'age': 7.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 21,
   'date': '2012-12-14',
   'name': 'Grace McDonnell',
   'gender': 'F',
   'age': 7.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 22,
   'date': '2012-12-14',
   'name': 'Adam Lanza',
   'gender': 'M',
   'age': 20.0,
   'ageGroup': 3.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 23,
   'date': '2012-12-14',
   'name': 'Victoria Soto',
   'gender': 'F',
   'age': 27.0,
   'ageGroup': 3.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 24,
   'date': '2012-12-14',
   'name': 'Rachel Davino',
   'gender': 'F',
   'age': 29.0,
   'ageGroup': 3.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 25,
   'date': '2012-12-14',
   'name': 'Lauren Rousseau',
   'gender': 'F',
   'age': 30.0,
   'ageGroup': 3.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 26,
   'date': '2012-12-14',
   'name': 'Dawn Hochsprung',
   'gender': 'F',
   'age': 47.0,
   'ageGroup': 3.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 27,
   'date': '2012-12-14',
   'name': 'Nancy Lanza',
   'gender': 'F',
   'age': 52.0,
   'ageGroup': 3.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 28,
   'date': '2012-12-14',
   'name': 'Anne Marie Murphy',
   'gender': 'F',
   'age': 52.0,
   'ageGroup': 3.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 29,
   'date': '2012-12-14',
   'name': 'Mary Sherlach',
   'gender': 'F',
   'age': 56.0,
   'ageGroup': 3.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 30,
   'date': '2012-12-14',
   'name': 'Matthew Nestle',
   'gender': 'M',
   'age': 18.0,
   'ageGroup': 3.0,
   'city': 'Pensacola',
   'state': 'FL',
   'lat': 30.421309,
   'lng': -87.2169149,
   'url': 'http://www.pnj.com/article/20121214/NEWS01/121214001/1-dead-1-arrested-Pensacola-shooting',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 31,
   'date': '2012-12-14',
   'name': 'Santino Mota',
   'gender': 'M',
   'age': 20.0,
   'ageGroup': 3.0,
   'city': 'Bay City',
   'state': 'MI',
   'lat': 43.5944677,
   'lng': -83.8888648,
   'url': 'http://www.mlive.com/news/bay-city/index.ssf/2013/06/trial_rescheduled_for_bay_coun_1.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 32,
   'date': '2012-12-14',
   'name': 'Roybin Lyn Griggs-Johnson',
   'gender': 'F',
   'age': 47.0,
   'ageGroup': 3.0,
   'city': 'Grand Rapids',
   'state': 'MI',
   'lat': 42.9633599,
   'lng': -85.6680863,
   'url': 'http://www.woodtv.com/dpp/news/local/grand_rapids/woman-shot-to-death-in-gr-home-on-prince-se-121512',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 33,
   'date': '2012-12-14',
   'name': 'Jessica Corinne Kenny',
   'gender': 'F',
   'age': 30.0,
   'ageGroup': 3.0,
   'city': 'Las Vegas',
   'state': 'NV',
   'lat': 36.145204,
   'lng': -115.1611806,
   'url': 'http://chicagoist.com/2012/12/18/las_vegas_casino_shooting_was_viole.php',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 34,
   'date': '2012-12-14',
   'name': 'Edward C. Brandt',
   'gender': 'M',
   'age': 31.0,
   'ageGroup': 3.0,
   'city': 'Las Vegas',
   'state': 'NV',
   'lat': 36.145204,
   'lng': -115.1611806,
   'url': 'http://www.staradvertiser.com/news/breaking/184021461.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 35,
   'date': '2012-12-14',
   'name': 'Randall Buford',
   'gender': 'M',
   'age': 21.0,
   'ageGroup': 3.0,
   'city': 'Jacksonville',
   'state': 'NC',
   'lat': 34.7540524,
   'lng': -77.4302415,
   'url': 'http://www.jdnews.com/news/local/marine-charged-in-fatal-shooting-has-first-appearance-1.66293?tc=cr',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 36,
   'date': '2012-12-14',
   'name': 'Hilma Barnett',
   'gender': 'F',
   'age': 86.0,
   'ageGroup': 3.0,
   'city': 'Marshall',
   'state': 'NC',
   'lat': 35.7973284,
   'lng': -82.6840252,
   'url': 'http://www.citizen-times.com/article/20121215/NEWS01/121215003/Madison-man-charged-slaying-wife-mother-law',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 37,
   'date': '2012-12-14',
   'name': 'Stephanie Lagrua',
   'gender': 'F',
   'age': 58.0,
   'ageGroup': 3.0,
   'city': 'Marshall',
   'state': 'NC',
   'lat': 35.7973284,
   'lng': -82.6840252,
   'url': 'http://www.citizen-times.com/article/20121215/NEWS01/121215003/Madison-man-charged-slaying-wife-mother-law',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 38,
   'date': '2012-12-14',
   'name': 'Lamine Wilson',
   'gender': 'M',
   'age': 32.0,
   'ageGroup': 3.0,
   'city': 'Toledo',
   'state': 'OH',
   'lat': 41.6786754,
   'lng': -83.5127283,
   'url': 'http://www.northwestohio.com/news/story.aspx?id=837605#.UNImgGMj6AF',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 39,
   'date': '2012-12-14',
   'name': 'Danny Lee Lamons',
   'gender': 'M',
   'age': 51.0,
   'ageGroup': 3.0,
   'city': 'Greeneville',
   'state': 'TN',
   'lat': 36.1631575,
   'lng': -82.8309861,
   'url': 'http://www.greenevillesun.com/Local_News/article/Richard-Murray-Faces-Murder-Charge-After-Fatal-Shooting-id-322399',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 40,
   'date': '2012-12-14',
   'name': 'Officer Martoiya Lang',
   'gender': 'F',
   'age': 32.0,
   'ageGroup': 3.0,
   'city': 'Memphis',
   'state': 'TN',
   'lat': 35.1490215,
   'lng': -90.0516285,
   'url': 'http://www.commercialappeal.com/news/2012/dec/15/no-headline---shooting_main/',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 41,
   'date': '2012-12-14',
   'name': 'Kelly David Bangle',
   'gender': 'M',
   'age': 30.0,
   'ageGroup': 3.0,
   'city': 'Fort Hood',
   'state': 'TX',
   'lat': 31.13,
   'lng': -97.78,
   'url': 'http://www.forthoodpresscenter.com/go/doc/3439/1659939/',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 42,
   'date': '2012-12-14',
   'name': 'Ralph Salazar',
   'gender': 'M',
   'age': 59.0,
   'ageGroup': 3.0,
   'city': 'Salt Lake County',
   'state': 'UT',
   'lat': 40.644188,
   'lng': -111.9522491,
   'url': 'http://www.sltrib.com/sltrib/news/55481701-78/fire-hoyal-investigators-upd.html.csp',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 43,
   'date': '2012-12-14',
   'name': 'Alice Griego',
   'gender': 'F',
   'age': 55.0,
   'ageGroup': 3.0,
   'city': 'Salt Lake County',
   'state': 'UT',
   'lat': 40.644188,
   'lng': -111.9522491,
   'url': 'http://www.sltrib.com/sltrib/news/55481701-78/fire-hoyal-investigators-upd.html.csp',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 1337,
   'date': '2012-12-14',
   'name': 'Omar Vargas',
   'gender': 'M',
   'age': 0.0,
   'ageGroup': 3.0,
   'city': 'Exeter',
   'state': 'CA',
   'lat': 36.2960613,
   'lng': -119.1420517,
   'url': 'http://www.kmph.com/story/20355702/gun-left-at-scene-of',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 2414,
   'date': '2012-12-14',
   'name': 0,
   'gender': 'M',
   'age': 25.0,
   'ageGroup': 3.0,
   'city': 'Detroit',
   'state': 'MI',
   'lat': 42.3486635,
   'lng': -83.0567375,
   'url': 'http://www.detroitmi.gov/Portals/0/docs/police/MCSR 12.14.pdf',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 1459,
   'date': '2012-12-14',
   'name': 'Lenny Ellis',
   'gender': 'M',
   'age': 30.0,
   'ageGroup': 3.0,
   'city': 'Oak Cliff',
   'state': 'TX',
   'lat': 29.7104586,
   'lng': -98.1460417,
   'url': 'http://www.wfaa.com/news/local/dallas/Officer-involved-shooting-at-Oak-Cliff-apartment-complex-183524741.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 1460,
   'date': '2012-12-14',
   'name': 'Joseph Oliva',
   'gender': 'M',
   'age': 58.0,
   'ageGroup': 3.0,
   'city': 'Cornwall',
   'state': 'NY',
   'lat': 40.7911785,
   'lng': -73.9748189433876,
   'url': 'http://westchester.news12.com/news/police-apparent-murder-suicide-in-cornwall-1.4337815',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 1461,
   'date': '2012-12-14',
   'name': 'Sandra Oliva',
   'gender': 'F',
   'age': 54.0,
   'ageGroup': 3.0,
   'city': 'Cornwall',
   'state': 'NY',
   'lat': 40.7911785,
   'lng': -73.9748189433876,
   'url': 'http://www.recordonline.com/apps/pbcs.dll/article?AID=/20121216/NEWS/212160328',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 200,
   'date': '2012-12-14',
   'name': 'Charles Hooten',
   'gender': 'M',
   'age': 39.0,
   'ageGroup': 3.0,
   'city': 'Conway',
   'state': 'AR',
   'lat': 35.076417,
   'lng': -92.4560746050616,
   'url': 'http://www.katv.com/story/23666951/conway-man-pleads-to-manslaughter-in-shooting-of-2',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 2318,
   'date': '2012-12-15',
   'name': 'Kathy Skellie',
   'gender': 'F',
   'age': 59.0,
   'ageGroup': 3.0,
   'city': 'Glens Falls',
   'state': 'NY',
   'lat': 43.3099598,
   'lng': -73.6442514,
   'url': 'http://www.foxnews.com/us/2012/12/18/new-york-man-who-allegedly-helped-wife-kill-self-charged-with-manslaughter/',
   'year': 2012,
   'day': 15,
   'month': 12,
   'timestamp': 734852},
  {'victimID': 2324,
   'date': '2012-12-15',
   'name': 0,
   'gender': 'M',
   'age': 0.0,
   'ageGroup': 3.0,
   'city': 'Richmond',
   'state': 'VA',
   'lat': 37.541239,
   'lng': -77.4420183,

In [99]:
#save the data as a json
with open('processed_gundeaths_data.json','w') as f:
    json.dump(all_data,f)
#test that it is saved and can be read properly
with open('processed_gundeaths_data.json','r') as f:
    test = json.load(f)
test

{'victims': [{'victimID': 1,
   'date': '2012-12-14',
   'name': 'Antida Archuleta',
   'gender': 'F',
   'age': 20.0,
   'ageGroup': 3.0,
   'city': 'Westminster',
   'state': 'CO',
   'lat': 39.8936685,
   'lng': -105.072111818405,
   'url': 'http://www.9news.com/rss/story.aspx?storyid=305252',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 2,
   'date': '2012-12-14',
   'name': 'Charlotte Bacon',
   'gender': 'F',
   'age': 6.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 3,
   'date': '2012-12-14',
   'name': 'Olivia Engel',
   'gender': 'F',
   'age': 6.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 4,
   'date': '2012-12-14',
   'name': 'Ana Marquez-Greene',
   'gender': 'F',
   'age': 6.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 5,
   'date': '2012-12-14',
   'name': 'Dylan Hockley',
   'gender': 'M',
   'age': 6.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 6,
   'date': '2012-12-14',
   'name': 'Madeline Hsu',
   'gender': 'F',
   'age': 6.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 7,
   'date': '2012-12-14',
   'name': 'Catherine Hubbard',
   'gender': 'F',
   'age': 6.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 8,
   'date': '2012-12-14',
   'name': 'Jesse Lewis',
   'gender': 'M',
   'age': 6.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 9,
   'date': '2012-12-14',
   'name': 'James Mattioli',
   'gender': 'M',
   'age': 6.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 10,
   'date': '2012-12-14',
   'name': 'Emilie Parker',
   'gender': 'F',
   'age': 6.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 11,
   'date': '2012-12-14',
   'name': 'Jack Pinto',
   'gender': 'M',
   'age': 6.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 12,
   'date': '2012-12-14',
   'name': 'Noah Pozner',
   'gender': 'M',
   'age': 6.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 13,
   'date': '2012-12-14',
   'name': 'Caroline Previdi',
   'gender': 'F',
   'age': 6.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 14,
   'date': '2012-12-14',
   'name': 'Jessica Rekos',
   'gender': 'F',
   'age': 6.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 15,
   'date': '2012-12-14',
   'name': 'Avielle Richman',
   'gender': 'F',
   'age': 6.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 16,
   'date': '2012-12-14',
   'name': 'Benjamin Wheeler',
   'gender': 'M',
   'age': 6.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 17,
   'date': '2012-12-14',
   'name': 'Allison Wyatt',
   'gender': 'F',
   'age': 6.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 18,
   'date': '2012-12-14',
   'name': 'Daniel Barden',
   'gender': 'M',
   'age': 7.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 10258,
   'date': '2012-12-14',
   'name': 'Debbie Ford',
   'gender': 'F',
   'age': 47.0,
   'ageGroup': 3.0,
   'city': 'Conway',
   'state': 'AR',
   'lat': 35.0886963,
   'lng': -92.4421011,
   'url': 'http://www.katv.com/story/23666951/conway-man-pleads-to-manslaughter-in-shooting-of-2',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 19,
   'date': '2012-12-14',
   'name': 'Josephine Gay',
   'gender': 'F',
   'age': 7.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 2323,
   'date': '2012-12-14',
   'name': 'Robert Hunt',
   'gender': 'M',
   'age': 57.0,
   'ageGroup': 3.0,
   'city': 'Chester',
   'state': 'OH',
   'lat': 39.0875777,
   'lng': -81.9226372,
   'url': 'http://www.wsaz.com/news/headlines/BREAKING-NEWS-Three-Shot-in-Meigs-County-Ohio-183542661.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 20,
   'date': '2012-12-14',
   'name': 'Chase Kowalski',
   'gender': 'M',
   'age': 7.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 21,
   'date': '2012-12-14',
   'name': 'Grace McDonnell',
   'gender': 'F',
   'age': 7.0,
   'ageGroup': 1.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 22,
   'date': '2012-12-14',
   'name': 'Adam Lanza',
   'gender': 'M',
   'age': 20.0,
   'ageGroup': 3.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 23,
   'date': '2012-12-14',
   'name': 'Victoria Soto',
   'gender': 'F',
   'age': 27.0,
   'ageGroup': 3.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 24,
   'date': '2012-12-14',
   'name': 'Rachel Davino',
   'gender': 'F',
   'age': 29.0,
   'ageGroup': 3.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 25,
   'date': '2012-12-14',
   'name': 'Lauren Rousseau',
   'gender': 'F',
   'age': 30.0,
   'ageGroup': 3.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 26,
   'date': '2012-12-14',
   'name': 'Dawn Hochsprung',
   'gender': 'F',
   'age': 47.0,
   'ageGroup': 3.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 27,
   'date': '2012-12-14',
   'name': 'Nancy Lanza',
   'gender': 'F',
   'age': 52.0,
   'ageGroup': 3.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 28,
   'date': '2012-12-14',
   'name': 'Anne Marie Murphy',
   'gender': 'F',
   'age': 52.0,
   'ageGroup': 3.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 29,
   'date': '2012-12-14',
   'name': 'Mary Sherlach',
   'gender': 'F',
   'age': 56.0,
   'ageGroup': 3.0,
   'city': 'Newtown',
   'state': 'CT',
   'lat': 41.4123225,
   'lng': -73.3114235802945,
   'url': 'http://www.cnn.com/2012/12/15/us/connecticut-shooting-victims/index.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 30,
   'date': '2012-12-14',
   'name': 'Matthew Nestle',
   'gender': 'M',
   'age': 18.0,
   'ageGroup': 3.0,
   'city': 'Pensacola',
   'state': 'FL',
   'lat': 30.421309,
   'lng': -87.2169149,
   'url': 'http://www.pnj.com/article/20121214/NEWS01/121214001/1-dead-1-arrested-Pensacola-shooting',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 31,
   'date': '2012-12-14',
   'name': 'Santino Mota',
   'gender': 'M',
   'age': 20.0,
   'ageGroup': 3.0,
   'city': 'Bay City',
   'state': 'MI',
   'lat': 43.5944677,
   'lng': -83.8888648,
   'url': 'http://www.mlive.com/news/bay-city/index.ssf/2013/06/trial_rescheduled_for_bay_coun_1.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 32,
   'date': '2012-12-14',
   'name': 'Roybin Lyn Griggs-Johnson',
   'gender': 'F',
   'age': 47.0,
   'ageGroup': 3.0,
   'city': 'Grand Rapids',
   'state': 'MI',
   'lat': 42.9633599,
   'lng': -85.6680863,
   'url': 'http://www.woodtv.com/dpp/news/local/grand_rapids/woman-shot-to-death-in-gr-home-on-prince-se-121512',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 33,
   'date': '2012-12-14',
   'name': 'Jessica Corinne Kenny',
   'gender': 'F',
   'age': 30.0,
   'ageGroup': 3.0,
   'city': 'Las Vegas',
   'state': 'NV',
   'lat': 36.145204,
   'lng': -115.1611806,
   'url': 'http://chicagoist.com/2012/12/18/las_vegas_casino_shooting_was_viole.php',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 34,
   'date': '2012-12-14',
   'name': 'Edward C. Brandt',
   'gender': 'M',
   'age': 31.0,
   'ageGroup': 3.0,
   'city': 'Las Vegas',
   'state': 'NV',
   'lat': 36.145204,
   'lng': -115.1611806,
   'url': 'http://www.staradvertiser.com/news/breaking/184021461.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 35,
   'date': '2012-12-14',
   'name': 'Randall Buford',
   'gender': 'M',
   'age': 21.0,
   'ageGroup': 3.0,
   'city': 'Jacksonville',
   'state': 'NC',
   'lat': 34.7540524,
   'lng': -77.4302415,
   'url': 'http://www.jdnews.com/news/local/marine-charged-in-fatal-shooting-has-first-appearance-1.66293?tc=cr',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 36,
   'date': '2012-12-14',
   'name': 'Hilma Barnett',
   'gender': 'F',
   'age': 86.0,
   'ageGroup': 3.0,
   'city': 'Marshall',
   'state': 'NC',
   'lat': 35.7973284,
   'lng': -82.6840252,
   'url': 'http://www.citizen-times.com/article/20121215/NEWS01/121215003/Madison-man-charged-slaying-wife-mother-law',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 37,
   'date': '2012-12-14',
   'name': 'Stephanie Lagrua',
   'gender': 'F',
   'age': 58.0,
   'ageGroup': 3.0,
   'city': 'Marshall',
   'state': 'NC',
   'lat': 35.7973284,
   'lng': -82.6840252,
   'url': 'http://www.citizen-times.com/article/20121215/NEWS01/121215003/Madison-man-charged-slaying-wife-mother-law',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 38,
   'date': '2012-12-14',
   'name': 'Lamine Wilson',
   'gender': 'M',
   'age': 32.0,
   'ageGroup': 3.0,
   'city': 'Toledo',
   'state': 'OH',
   'lat': 41.6786754,
   'lng': -83.5127283,
   'url': 'http://www.northwestohio.com/news/story.aspx?id=837605#.UNImgGMj6AF',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 39,
   'date': '2012-12-14',
   'name': 'Danny Lee Lamons',
   'gender': 'M',
   'age': 51.0,
   'ageGroup': 3.0,
   'city': 'Greeneville',
   'state': 'TN',
   'lat': 36.1631575,
   'lng': -82.8309861,
   'url': 'http://www.greenevillesun.com/Local_News/article/Richard-Murray-Faces-Murder-Charge-After-Fatal-Shooting-id-322399',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 40,
   'date': '2012-12-14',
   'name': 'Officer Martoiya Lang',
   'gender': 'F',
   'age': 32.0,
   'ageGroup': 3.0,
   'city': 'Memphis',
   'state': 'TN',
   'lat': 35.1490215,
   'lng': -90.0516285,
   'url': 'http://www.commercialappeal.com/news/2012/dec/15/no-headline---shooting_main/',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 41,
   'date': '2012-12-14',
   'name': 'Kelly David Bangle',
   'gender': 'M',
   'age': 30.0,
   'ageGroup': 3.0,
   'city': 'Fort Hood',
   'state': 'TX',
   'lat': 31.13,
   'lng': -97.78,
   'url': 'http://www.forthoodpresscenter.com/go/doc/3439/1659939/',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 42,
   'date': '2012-12-14',
   'name': 'Ralph Salazar',
   'gender': 'M',
   'age': 59.0,
   'ageGroup': 3.0,
   'city': 'Salt Lake County',
   'state': 'UT',
   'lat': 40.644188,
   'lng': -111.9522491,
   'url': 'http://www.sltrib.com/sltrib/news/55481701-78/fire-hoyal-investigators-upd.html.csp',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 43,
   'date': '2012-12-14',
   'name': 'Alice Griego',
   'gender': 'F',
   'age': 55.0,
   'ageGroup': 3.0,
   'city': 'Salt Lake County',
   'state': 'UT',
   'lat': 40.644188,
   'lng': -111.9522491,
   'url': 'http://www.sltrib.com/sltrib/news/55481701-78/fire-hoyal-investigators-upd.html.csp',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 1337,
   'date': '2012-12-14',
   'name': 'Omar Vargas',
   'gender': 'M',
   'age': 0.0,
   'ageGroup': 3.0,
   'city': 'Exeter',
   'state': 'CA',
   'lat': 36.2960613,
   'lng': -119.1420517,
   'url': 'http://www.kmph.com/story/20355702/gun-left-at-scene-of',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 2414,
   'date': '2012-12-14',
   'name': 0,
   'gender': 'M',
   'age': 25.0,
   'ageGroup': 3.0,
   'city': 'Detroit',
   'state': 'MI',
   'lat': 42.3486635,
   'lng': -83.0567375,
   'url': 'http://www.detroitmi.gov/Portals/0/docs/police/MCSR 12.14.pdf',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 1459,
   'date': '2012-12-14',
   'name': 'Lenny Ellis',
   'gender': 'M',
   'age': 30.0,
   'ageGroup': 3.0,
   'city': 'Oak Cliff',
   'state': 'TX',
   'lat': 29.7104586,
   'lng': -98.1460417,
   'url': 'http://www.wfaa.com/news/local/dallas/Officer-involved-shooting-at-Oak-Cliff-apartment-complex-183524741.html',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 1460,
   'date': '2012-12-14',
   'name': 'Joseph Oliva',
   'gender': 'M',
   'age': 58.0,
   'ageGroup': 3.0,
   'city': 'Cornwall',
   'state': 'NY',
   'lat': 40.7911785,
   'lng': -73.9748189433876,
   'url': 'http://westchester.news12.com/news/police-apparent-murder-suicide-in-cornwall-1.4337815',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 1461,
   'date': '2012-12-14',
   'name': 'Sandra Oliva',
   'gender': 'F',
   'age': 54.0,
   'ageGroup': 3.0,
   'city': 'Cornwall',
   'state': 'NY',
   'lat': 40.7911785,
   'lng': -73.9748189433876,
   'url': 'http://www.recordonline.com/apps/pbcs.dll/article?AID=/20121216/NEWS/212160328',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 200,
   'date': '2012-12-14',
   'name': 'Charles Hooten',
   'gender': 'M',
   'age': 39.0,
   'ageGroup': 3.0,
   'city': 'Conway',
   'state': 'AR',
   'lat': 35.076417,
   'lng': -92.4560746050616,
   'url': 'http://www.katv.com/story/23666951/conway-man-pleads-to-manslaughter-in-shooting-of-2',
   'year': 2012,
   'day': 14,
   'month': 12,
   'timestamp': 734851},
  {'victimID': 2318,
   'date': '2012-12-15',
   'name': 'Kathy Skellie',
   'gender': 'F',
   'age': 59.0,
   'ageGroup': 3.0,
   'city': 'Glens Falls',
   'state': 'NY',
   'lat': 43.3099598,
   'lng': -73.6442514,
   'url': 'http://www.foxnews.com/us/2012/12/18/new-york-man-who-allegedly-helped-wife-kill-self-charged-with-manslaughter/',
   'year': 2012,
   'day': 15,
   'month': 12,
   'timestamp': 734852},
  {'victimID': 2324,
   'date': '2012-12-15',
   'name': 0,
   'gender': 'M',
   'age': 0.0,
   'ageGroup': 3.0,
   'city': 'Richmond',
   'state': 'VA',
   'lat': 37.541239,
   'lng': -77.4420183,